# NOTE: To use this, uncomment out all the below lines and
# rename file to dependabot.yml

# version: 2
# updates:
#   - package-ecosystem: "pip"
#     # Files stored in repository root
#     directory: "/"
#     schedule:
#       interval: "monthly"
#     reviewers:
#       - "niharikasingh"

#   - package-ecosystem: "npm"
#     # Files stored in `app` directory
#     directory: "/"
#     schedule:
#       interval: "monthly"
#     reviewers:
#       - "niharikasingh"
#     ignore:
#       - dependency-name: "@eto*"
#       - dependency-name: "@mdx-js*"
#       - dependency-name: "gatsby*"

#   - package-ecosystem: "github-actions"
#     # Workflow files stored in the
#     # default location of `.github/workflows`
#     directory: "/"
#     schedule:
#       interval: "monthly"
#     reviewers:
#       - "niharikasingh"
